version: "3"
services:
  app:
    build:
      context: ./
      args:
        - TZ=${TZ}
    volumes:
      - .:/var/www
      - ./logs:/var/log/php
      - ./php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/src
    ports:
      - "8080:8080"
    networks:
      - my_network
networks:
  my_network:
    external: true